Disable attestation
I got this error:

    ERROR: failed to build: Attestation is not supported for the docker driver.
    Switch to a different driver, or turn on the containerd image store, and try again.

I'll need to look into that, but it's not like goss has SBOMs yet
anyway...